CREATE TABLE "pais" (
    "pais_id" varchar(3) PRIMARY KEY,
    "nombre_pais" varchar(100) NOT NULL,
    "region" varchar(100)
);

CREATE TABLE "poblacion" (
    "pais_id" varchar(3),
    "anio" int,
    "poblacion" bigint,
    PRIMARY KEY ("pais_id", "anio")
);

CREATE TABLE "atleta" (
    "atleta_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nombre_completo" varchar(255) NOT NULL,
    "nombre_usado" varchar(255),
    "sexo" varchar(1),
    "fecha_nacimiento" date,
    "lugar_nacimiento" varchar(255),
    "fecha_fallecimiento" date,
    "lugar_fallecimiento" varchar(255),
    "estatura_cm" int,
    "peso_kg" int,
    "pais_id" varchar(3)
);

CREATE TABLE "edicion" (
    "edicion_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nombre_edicion" varchar(100) NOT NULL,
    "anio" int NOT NULL,
    "temporada" varchar(10) NOT NULL,
    "ciudad" varchar(100),
    "pais_sede_id" varchar(3)
);

CREATE TABLE "deporte" (
    "deporte_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nombre_deporte" varchar(100) UNIQUE NOT NULL
);

CREATE TABLE "evento" (
    "evento_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "edicion_id" int NOT NULL,
    "deporte_id" int NOT NULL,
    "nombre_evento" varchar(255) NOT NULL
);

CREATE TABLE "equipo" (
    "equipo_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "evento_id" int NOT NULL,
    "pais_id" varchar(3),
    "nombre_equipo" varchar(150)
);

CREATE TABLE "club" (
    "club_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nombre_club" varchar(255) NOT NULL,
    "pais_id" varchar(3)
);

CREATE TABLE "atleta_club" (
    "atleta_id" int,
    "club_id" int,
    PRIMARY KEY ("atleta_id", "club_id")
);

CREATE TABLE "participacion" (
    "participacion_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "atleta_id" int NOT NULL,
    "evento_id" int NOT NULL,
    "equipo_id" int,
    "pais_representado_id" varchar(3),
    "nombre_en_competencia" varchar(255),
    "posicion" varchar(20),
    "medalla" varchar(10)
);

ALTER TABLE "poblacion"
    ADD FOREIGN KEY ("pais_id") REFERENCES "pais" ("pais_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "atleta"
    ADD FOREIGN KEY ("pais_id") REFERENCES "pais" ("pais_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "edicion"
    ADD FOREIGN KEY ("pais_sede_id") REFERENCES "pais" ("pais_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "evento"
    ADD FOREIGN KEY ("edicion_id") REFERENCES "edicion" ("edicion_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "evento"
    ADD FOREIGN KEY ("deporte_id") REFERENCES "deporte" ("deporte_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "equipo"
    ADD FOREIGN KEY ("evento_id") REFERENCES "evento" ("evento_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "equipo"
    ADD FOREIGN KEY ("pais_id") REFERENCES "pais" ("pais_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "club"
    ADD FOREIGN KEY ("pais_id") REFERENCES "pais" ("pais_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "atleta_club"
    ADD FOREIGN KEY ("atleta_id") REFERENCES "atleta" ("atleta_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "atleta_club"
    ADD FOREIGN KEY ("club_id") REFERENCES "club" ("club_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "participacion"
    ADD FOREIGN KEY ("atleta_id") REFERENCES "atleta" ("atleta_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "participacion"
    ADD FOREIGN KEY ("evento_id") REFERENCES "evento" ("evento_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "participacion"
    ADD FOREIGN KEY ("equipo_id") REFERENCES "equipo" ("equipo_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "participacion"
    ADD FOREIGN KEY ("pais_representado_id") REFERENCES "pais" ("pais_id") DEFERRABLE INITIALLY IMMEDIATE;

